Traceback (most recent call last):
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_heto_model.py", line 165, in <module>
    main(args.input_folder, args.graph_file, int(args.epochs), float(args.lamb))
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_heto_model.py", line 113, in main
    glist, _ = dgl.load_graphs(os.path.join(input_folder, graph_file))
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 186, in load_graphs
    check_local_file_exists(filename)
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 40, in check_local_file_exists
    raise DGLError("File {} does not exist.".format(filename))
dgl._ffi.base.DGLError: File saved_graphs/google_command/clique/filter/full_weighted/phon_art/hetero_graph_43_1_43_1500.dgl does not exist.
Traceback (most recent call last):
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_heto_link_pred_model.py", line 244, in <module>
    main(args.input_folder, args.graph_file, int(args.epochs), float(args.lamb), args.dataset)
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_heto_link_pred_model.py", line 172, in main
    glist, _ = dgl.load_graphs(os.path.join(input_folder, graph_file))
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 186, in load_graphs
    check_local_file_exists(filename)
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 40, in check_local_file_exists
    raise DGLError("File {} does not exist.".format(filename))
dgl._ffi.base.DGLError: File saved_graphs/google_command/clique/filter/full_weighted/phon_art/hetero_graph_43_1_43_1500.dgl does not exist.
Traceback (most recent call last):
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_heto_model.py", line 165, in <module>
    main(args.input_folder, args.graph_file, int(args.epochs), float(args.lamb))
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_heto_model.py", line 113, in main
    glist, _ = dgl.load_graphs(os.path.join(input_folder, graph_file))
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 186, in load_graphs
    check_local_file_exists(filename)
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 40, in check_local_file_exists
    raise DGLError("File {} does not exist.".format(filename))
dgl._ffi.base.DGLError: File saved_graphs/google_command/clique/filter/full_weighted/phon_count/hetero_graph_43_1_43_1500.dgl does not exist.
Traceback (most recent call last):
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_heto_link_pred_model.py", line 244, in <module>
    main(args.input_folder, args.graph_file, int(args.epochs), float(args.lamb), args.dataset)
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_heto_link_pred_model.py", line 172, in main
    glist, _ = dgl.load_graphs(os.path.join(input_folder, graph_file))
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 186, in load_graphs
    check_local_file_exists(filename)
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 40, in check_local_file_exists
    raise DGLError("File {} does not exist.".format(filename))
dgl._ffi.base.DGLError: File saved_graphs/google_command/clique/filter/full_weighted/phon_count/hetero_graph_43_1_43_1500.dgl does not exist.
